### ISSUE TITLE
Mismatch between trace ids reported by AWS ALB and application

### ISSUE THREAD

**Issue by otbe** [aws-observability/aws-otel-java-instrumentation#105]
**Describe the bug**
Im not quite sure if this ever worked with AWS ADOT but with the old Xray instrumentation it did.
We're running a quite simple and typical setup, an AWS ALB in front of a ECS Fargate task that runs our application.

We use the latest version of the AWS flavoured java agent (1.7) and version 0.13.0 of the AWS flavoured otel collector as a sidecar.
We turned on LB logs (s3) in order to have more insights into requests. It appears that not a single trace id mentioned in LB logs is visible within our application logs. 

With the former Xray setup we could basically search for a trace id in our log frontend and would get both, the application logs and the corresponding LB log.

Apart from the java agent we only use the AwsXrayPropagator to inject the trace id back into our response. Something along these lines
```java
public class XrayTraceIdHeaderFilter extends OncePerRequestFilter {
  @Override
  protected void doFilterInternal(
      HttpServletRequest request, HttpServletResponse response, FilterChain chain)
      throws ServletException, IOException {

    AwsXrayPropagator.getInstance()
        .inject(Context.current(), response, HttpServletResponse::setHeader);

    chain.doFilter(request, response);
  }
}
```

Is there something else I have to do in order to get this working again?

Additional notes:
- app is a spring boot service; SB 2.5.5
- java agent 1.7.0 
- otel collector 0.13.0

**Comment by anuraaga** [comment]
Hi @otbe - this hasn't ever worked with ADOT. The ELB only sends a trace ID, not a full trace context (trace ID + span ID + sampling decision) to the server. Because the OpenTelemetry specification treats such a context as invalid, it gets dropped. Concretely, the parent context must be valid here

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/SdkSpanBuilder.java#L174

and it's not possible for the tracer to reuse the trace ID if there is no span ID.

We haven't come up with a good way to deal with this unfortunately as it's a gap between the X-Ray's trace header and OpenTelemetry at the spec level. This is definitely something we want to address in the future though.

**Comment by otbe** [comment]
Thank you very much for your answer. Is there a place where I can subscribe myself in order to stay up2date in this regards?
