### ISSUE TITLE
Latest Spark sample app breaks the CI test-cases

### ISSUE THREAD

**Issue by Kausik-A** [aws-observability/aws-otel-java-instrumentation#187]
**Describe the bug**

Latest Spark sample app breaks some of the CI test-cases. The run is linked [here](https://github.com/aws-observability/aws-otel-collector/actions/runs/2499291381) 

**Steps to reproduce**

Include `sample_app_image = "public.ecr.aws/aws-otel-test/aws-otel-java-spark:latest"` in testcases that use the `spark sample app`

**What did you expect to see?**

The test-case passing

**What did you see instead?**

The validator fails to verify the data

**Comment by rapphil** [comment]
This is a testcase that is using the problematic image: https://github.com/aws-observability/aws-otel-test-framework/blob/622aadadd3faaf5fadf2f3272bfd6358f48d48e8/terraform/testcases/otlp_http_exporter_trace_mock/parameters.tfvars

**Comment by rapphil** [comment]
This testcase uses the referenced image:
https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/terraform/testcases/otlp_http_exporter_metric_mock/parameters.tfvars


https://github.com/aws-observability/aws-otel-collector/actions/runs/3070344837/jobs/5006504847
It was used in this CI run that was fully successful 16 days ago. I suspect that whatever was the problem with the image, it got solved.

**Comment by rapphil** [comment]
Latest CI run looks successful for the usage of the spark app and is failing on something else it seems.

**Comment by bryan-aguilar** [comment]
I do not think all collector tests are using the same version of the spark sample app.

**Comment by rapphil** [comment]
I tried to find an instance where the latest image was not used but I could not find. Do you have the link for one?

**Comment by rapphil** [comment]
I double checked and all test cases are using the latest version of the spark java sample app, which is updated here: https://github.com/aws-observability/aws-otel-java-instrumentation/blob/main/.github/workflows/main-build.yml#L52

**Comment by bryan-aguilar** [comment]
Here are two different testcases using two different sample apps.
1. [otlp_mock](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/terraform/testcases/otlp_mock/parameters.tfvars)
2. [otlp_metric](https://github.com/aws-observability/aws-otel-test-framework/blob/terraform/terraform/testcases/otlp_metric/parameters.tfvars)


When `sample_app_image` is defined it overrides `sample_app`. When only `sample_app` is defined it defines in image stored in a private ECR repo `otel-test/sample-apps/spark-latest`. This causes problems because the private ECR images are not managed by CI/CD. This also causes more issues when different image versions/manifests are used in different regions.
