### ISSUE TITLE
Clarify requirements for context propagation to xray

### ISSUE THREAD

**Issue by jack-berg** [aws-observability/aws-otel-java-instrumentation#207]
I'm trying to determine how exactly an `OpenTelemetrySdk` needs to be configured in order to propagate trace context from an application to AWS services. Here's a scenario:

- I have a Java app using the the OpenTelemetry SDK
- The app initializes traces, and makes calls to AWS services via the AWS SDK
- The app exports spans to a tracing backend, say Jaeger or some vendor backend
- I expect the traces to continue within the AWS service boundaries
- I expect to be able to export spans (segments) from XRay representing the parts of the trace inside AWS service boundaries, with IDs that allow me to complete the traces started in the app

Is it possible to achieve this setup using by configuring `OpenTelemetrySdk` to use the [AwsXrayPropagator](https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/aws/src/main/java/io/opentelemetry/extension/aws/AwsXrayPropagator.java) and / or [AwsXrayIdGenerator](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/aws-xray/src/main/java/io/opentelemetry/contrib/awsxray/AwsXrayIdGenerator.java) extensions? Is it sufficient to only configure the `AwsXrayPropagator` - will xray be able to recognize segments if `AwsXrayIdGenerator` wasn't used?

**Comment by rapphil** [comment]
Hi Jack, 

Your use case should be supported by Xray. I tried to reproduce the scenario that you described locally and it worked. 
The constraints are:

* The trace id has to be in the [format expected by xray](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-sendingdata.html#xray-api-traceids) therefore the trace id has to be generated using the [AwsXrayIIdGenerator](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/aws-xray/src/main/java/io/opentelemetry/contrib/awsxray/AwsXrayIdGenerator.java)
* The [AwsXrayPropagator](https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/aws/src/main/java/io/opentelemetry/extension/aws/AwsXrayPropagator.java)  has to be used in any service interfacing with AWS services.

**Comment by jack-berg** [comment]
Ok, quick clarifying followup question. The otel java agent [packages](do we absolutely want to treat custom events the same way as events in domains that are defined in OTel semantic conventions? I am thinking similar to our built-in events which follow some rules vs custom events that can be anything
Not necessarily, but treating them differently would create) the `AwsXrayPropagator`, but not the `AwsXrayIdGenerator`. If someone uses this distribution and enabled the aws context propagator, but not the id generation, what would you expect to happen? 

Based on your answer, I suppose I'd expect the trace to be broken since an invalid id would be provided via the `X-Amzn-Trace-Id` header. Is there any value to enabling aws compatible context propagation without using aws compatible id generation everywhere in the trace?

**Comment by rapphil** [comment]
Yes, if the traces need to be ingested into xray, the trace id needs to be in the xray format.

So there are some details around this issue. The `AwsXrayIdGenerator` has to be used only in the service that receive the request, and therefore generate the trace id. Any subsequent service can use a different id generator because in this case the trace id will not change, only the span id right?

Suppose the following scenario where we have three difference services connected to each other using http requests.

client -> A -> B -> C -> AWS Service.

`AwsXrayIdGenerator` has to be used only in `A`. `A` does not need to use `AwsXrayPropagator`. In this example it can propagate context to `B` using W3C for example. However in `C`, we have to use  `AwsXrayPropagator` because it will interact with an AWS service that will need to parse the xray headers.

I'm not sure if this makes any difference to you, but I thought that it was important to call this out.

**Comment by jack-berg** [comment]
Thanks for that summary! Super useful to have that in one place.
