### ISSUE TITLE
jar v1.30 has high severity Prisma vulnerability (CVE-2022-25857) associated with otel (OpenTelemetry Java Agent) v1.17.0

### ISSUE THREAD

**Issue by joroddy** [aws-observability/aws-otel-java-instrumentation#208]
jar v1.30 has high severity Prisma vulnerability (CVE-2022-25857) associated with otel (OpenTelemetry Java Agent) v1.17.0. org.yaml_snakeyaml at path:/opt/aws/aws-opentelemetry-agent.jar

Please remediate Prisma vulnerability. Thank you!
![otel vulnerability](https://user-images.githubusercontent.com/82471001/191507385-55fd1ed0-275a-494e-935c-b5b14d629f30.PNG)

**Comment by rapphil** [comment]
Hi, 

Thank you for reaching out.

As per our [guidelines](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/main/CONTRIBUTING.md#security-issue-notifications) we ask you not to create a public issue on this GitHub repo but rather the AWS/Amazon Security via our [vulnerability reporting page](http://aws.amazon.com/security/vulnerability-reporting/). Now, since this issue exists already, we can share with you that a patch for this vulnerability is now available via [aws-otel-java-instrumentation-v1.18.0](https://github.com/aws-observability/aws-otel-java-instrumentation/releases/tag/v1.18.0)
