### ISSUE TITLE
After switch to v1.19.2 disabling resource providers not working

### ISSUE THREAD

**Issue by SodaDev** [aws-observability/aws-otel-java-instrumentation#262]
**Describe the bug**
After switching to the v1.19.2 I can't disable resource providers with `
-Dotel.java.disabled.resource.providers=io.opentelemetry.sdk.extension.resources.ProcessResourceProvider,io.opentelemetry.sdk.extension.resources.ProcessRuntimeResourceProvider,io.opentelemetry.sdk.extension.resources.OsResourceProvider`

Tried to use newer packages from:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/v1.19.2/instrumentation/resources/library

**Steps to reproduce**
Run any instrumentation with above parameter

**What did you expect to see?**
No process and os attributes on the traces collected

**What did you see instead?**
Process and os attributes on the traces collected

**Comment by rapphil** [comment]
Hi, it seems that there is a typo in your system property. It should be `otel.java.disabled.resource-providers` instead of `Dotel.java.disabled.resource.providers`. [Reference](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#disabling-automatic-resourceproviders)

Moreover, the classes in 1.21.0 were changed and as result you need to update the values of your property. The list of aws resources can be find in this file: https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/aws-resources/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider

Finally, I recommend that you use the allow list approach instead of the block list approach, i.e.: use `otel.java.enabled.resource-providers` so that you set the resource providers that you want explicitly. If you want do disable all resource providers you can use `none` as value for that property.

**Comment by rapphil** [comment]
Closing the ticket as the question was addressed. Please reopen in case you still have questions.
