### ISSUE TITLE
Support for SQS

### ISSUE THREAD

**Issue by HashemTaheriSonos** [aws-observability/aws-otel-java-instrumentation#62]
**Is your feature request related to a problem? Please describe.**
So actually I have a question, is SQS supported by the agent fully?
Because currently I have a queue between my services, and by using the java agent, the service map is representing only one SQS queue, without any in or outflow from it to my actual services. while in the pet clinic sample app or other places, we have a nice representation which shows the queue exactly between the two services which pushing or receiving msg from it.

**Describe the solution you'd like**
Support for the SQS and be able to have the same visualization and representation of sqs.

Thanks in advance

**Comment by HashemTaheriSonos** [comment]
@anuraaga Do you know if there is a limitation over the number of traces which AWS service map be able to compute the service map between services?

because currently, I tested a very simple sqs app (instrumented with java agent), which I just simply push and receive a msg from it, and the Service Lens could nicely represent the flow.
like:
`client ------->AmazonSQS ----->SQSQueue`

but when adding the agent to our production services which are making way more traces, The service map, just shows sth like below while nature is the same, two services and an sqs between them:
`client ------> SQS (EC2 instance)`
and then in details of the traces, still I can see both get/send or delete are available, seems like somehow they are merged and get represented as a single service. 

I'm wondering if this is because the number of traces is too much that the service map cannot compute the relations and somehow fall back to a simple view.

**Comment by HashemTaheriSonos** [comment]
so to have a better idea, this is how it looks like in Cloudwatch->ServiceLens->Service Map
<img width="728" alt="fig" src="https://user-images.githubusercontent.com/80122300/124739774-792bf600-df1a-11eb-8d20-e0515f8dd724.png">

it's getting represented as EC2 instance and kind of all the sqs msg are merged and represented as this single entity, while if I check the traces, there are geturl or ReceiveMessage or send traces available for the different sqs that we have.

is this normal to have such a representation for many sqs?

**Comment by willarmiros** [comment]
Hi @HashemTaheriSonos,

This is strange behavior that you're seeing the SQS queue as a separate root node and not connected to your original app. Are you generating a server span in the app from which you're sending a message to SQS? Maybe a link to the source code of your sample app would help.

As for the incorrect labelling of EC2 instance, that may be a bug in an old version of the collector. Could you try upgrading to the latest version of the Otel Java agent and the latest aws-otel-collector (v0.11.0)?

**Comment by HashemTaheriSonos** [comment]
@willarmiros Thanks for your response, well I updated the aws-otel-collector to the latest (v0.11.0), however still have the same behavior.

We are using the java auto-instrumentation agent ([the one provided by aws version v1.1.0](https://github.com/aws-observability/aws-otel-java-instrumentation/tags)) with our Scala code.

and that's how it looks like.
the sqs is represented as EC2 while including the correct traces, (basically all the requests have trace id)

In addition, These queues are between different services, while they are all represented as a single EC2 instance and the relationship is broken. 

this is how it looks like if I go to trace of the sqs. (*I covered some parts with white boxes, otherwise, they are set correctly!)
![trace](https://user-images.githubusercontent.com/80122300/125304889-3c06a000-e32e-11eb-8e1f-8202bdc53d33.jpg)

![receive](https://user-images.githubusercontent.com/80122300/125306486-8e948c00-e32f-11eb-96e8-817fd6aaa131.jpg)

(it would've be great if the latest aws otel java agent has been released. because the v1.2.0 has the memory leak issue from the otel side, and the 1.3.1 including the fix for that, however, as I checked the merged failed on the [GitHub repo](https://github.com/aws-observability/aws-otel-java-instrumentation))

**Comment by willarmiros** [comment]
@HashemTaheriSonos I guess I'm still a bit confused on your expected service map:

```
client ------->AmazonSQS ----->SQSQueue
```

Does this mean `AmazonSQS` is your service that publishes to the queue, and SQSQueue is the queue itself? Also, what version of the AWS SDK are you using? In general, some producer & consumer code to reproduce the problem vs. what the expected behavior is would be helpful!

**Comment by HashemTaheriSonos** [comment]
@willarmiros sorry for the confusion, so I expect to have sth similar to the below figure:

![expected](https://user-images.githubusercontent.com/80122300/125470042-249b8852-d8ac-4587-9ebc-7980acd90e1a.jpeg)

But what's happening actually is:

![actual](https://user-images.githubusercontent.com/80122300/125470217-526209bd-cc8b-48e4-b17c-766c342051a1.jpg)

The AWS Java SDK that we are using is 2.15.79

regarding the code, I'm working on it to create a simple example, will share it as soon as I implement it.

**Comment by willarmiros** [comment]
@anuraaga we'll probably need the repro code to debug further, but this seems to be a bug in the AWS SDK v2 instrumentation for the Otel Java agent - at least in the context propagation. 

@HashemTaheriSonos thank you for the clarification. I'm assuming the nodes with the blocked out names are the services you have running on EC2? To give some background on the expected behavior, the producer node connecting to the queue node should be done automatically by the java agent. So this part should work by default:

```
                   SQS 1
                   /
client -> service 1 
                   \
                   SQS 2
```

The consumer side (services 2 & 3) being connected appears to be a feature we've implemented in the [AWS SDK V1 instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/5cbade4f429d3c4e7ea18308244defe1a83fa296/instrumentation/aws-sdk/aws-sdk-1.11/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v1_11/TracingRequestHandler.java), but not in [AWS SDK V2](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/5cbade4f429d3c4e7ea18308244defe1a83fa296/instrumentation/aws-sdk/aws-sdk-2.2/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v2_2/TracingExecutionInterceptor.java). @anuraaga can confirm this, in which case this would be a valid feature request. You can manually work around this in the meantime by recovering the span context from the SQS message system attributes and using it to start a span, as is done in [this example](https://docs.aws.amazon.com/xray/latest/devguide/xray-services-sqs.html#xray-services-sqs-retrieving) (but this uses the X-Ray SDK instead of the OTel SDK).

**Comment by HashemTaheriSonos** [comment]
@willarmiros Thanks for the explanation. 
But it becomes even more complicated then :D

because the blocked out names were not actually the services by themselves. they were the connection, for instance, the connections from the service to the docdb which is getting traced. so what's happening now is more like below and the services are not getting represented as an entity by themselves.

```
                  SQS 1
                   /
client -> 
                   \
                   SQS 2
                   
client ->     docdb
```

 
![docdb](https://user-images.githubusercontent.com/80122300/125925624-ea4796c0-1eab-411b-a2f7-d68578ede2b2.jpg)

While I guess based on your explanation it should be like:


```       
client ->  service-name ->   docdb
```

btw to find more, I tried to implement a simple java program which send a msg to sqs and recieve from it then added the javaagent to it, here is what I can observe in service lens, **do you confirm that this is the right represntation?**
 (bc I expected to see the program(service) name in here also while we don't have it) :

<img width="675" alt="Screenshot 2021-07-16 at 11 45 00" src="https://user-images.githubusercontent.com/80122300/125946156-2e417d63-78bb-47c8-9a4c-f9f0b31e0c2d.png">

I used aws sdk V1 (1.11.106), and adot collector + adot javaagent

**Comment by HashemTaheriSonos** [comment]
> we've implemented in the [AWS SDK V1 instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/5cbade4f429d3c4e7ea18308244defe1a83fa296/instrumentation/aws-sdk/aws-sdk-1.11/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v1_11/TracingRequestHandler.java), but not in [AWS SDK V2](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/5cbade4f429d3c4e7ea18308244defe1a83fa296/instrumentation/aws-sdk/aws-sdk-2.2/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v2_2/TracingExecutionInterceptor.java). @anuraaga can confirm this

@anuraaga As I checked, that's true and just in case of SDK v1 we have the correct behaviour and a full representation of a flow for a msg been send to an sqs connected to the consumer side.

Do you know when are we going to have the fix also for the SDK V2?

**Comment by willarmiros** [comment]
@HashemTaheriSonos we cannot provide ETAs on upcoming features or bug fixes, however I would encourage you to open a separate issue in the https://github.com/open-telemetry/opentelemetry-java-instrumentation repo, since that is where the AWS SDK v2 instrumentation actually lives and this issue is getting quite cluttered.

**Comment by HashemTaheriSonos** [comment]
@willarmiros I see... As you suggested I just created [an issue](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3684) there. Thank you

**Comment by HashemTaheriSonos** [comment]
This issue has been solved 
+ https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3684
